services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    env_file:
      - .env 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMINUSERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMINPASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - server

  mongo_express:
    image: mongo-express:1.0.2-20-alpine3.19
    env_file:
      - .env 
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ADMINPASSWORD}
    ports:
      - "${DATABASE_WEB_INTERFACE_PORT}:8081"
    depends_on:
      - mongodb
    networks:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    env_file:
      - .env 
    ports:
      - "${HOST_PORT}:${PORT}"
    depends_on:
      - mongodb

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - server

volumes:
  mongo-data:

# Wone network
networks:
  server:
    driver: bridge