name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or 'develop', depending on your workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Deploy to development server via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        source: "dist/"            # or 'build/', depending on your project
        target: "/var/www/my-app"  # Change to your desired path

    - name: SSH and restart app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        script: |
          cd /var/www/my-app
          pm2 restart app || pm2 start dist/index.js --name app
